# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

addons:
  sauce_connect:
    username: cordova
  jwt:
    # SAUCE_ACCESS_KEY
    secure: "3ZtWdybHvGm9uVJjMeMfGcbptdI+9xALUt8T5iLZWFE6yE10ulP4Svn7RvtCspQVRqKdmDeAHmKl8Rm84WQCh+hy2N9Vn4CW+ZfVg2R5/DAgG3ChMWcDOggoPMtr9I8iw8GLz6/78CY+RV+QOunRsUhTrjiSiegWek+0BUuz4rV9n4VVJJ3r63HXkY1ylJJpSOrQf/ZbXW/fz33Inlk5LUhAokjrD2NsrMtcMFcketFo4s61qu/SyRmD/vwi2dWhDUqLyiOFyWGr85h6zIYifniep72ijsD/v7gw3yM+yePStHAwgMaM3DMxnMmiikYGE4WSRwU79lxmug7VmbSYdZxNztwnrCr3Yy82wFmahDC/tQcNb+XdCLD1qrGhVR26KBDbHVBtK/PJLq8gQ+rZrX2qTm7aNsasw65rHgRGxaj5ndYBNM+0Kgwk+s0SrwRw49fHjaZYCqGLooedlYT7KU/iYtl8ysdrP/QHJ+sv1lkRnkgE9NQ3egiwAS91Jc/BQ960M1GVCxGJ+sF6s1FwUHZd1i3wm5qL1JUfKzTvNCj1XHdFFIq/GEYUTsDuAW3vbQPSt+GU4bETz1N4d9tCEgh5DFvbtH1TyDVmayFl/ZVGggPOK+wm+HCdjlKXaS+JVGQIHtRncTyUlhKWtaFrO7dlRvDbz3DcW9l6qq7kDGQ="

env:
  global:
    - SAUCE_USERNAME=cordova
    - TRAVIS_NODE_VERSION=12
    - ANDROID_API_LEVEL=29
    - ANDROID_BUILD_TOOLS_VERSION=29.0.2

language: node_js
node_js: 12

# yaml anchor/alias: https://medium.com/@tommyvn/travis-yml-dry-with-anchors-8b6a3ac1b027

_ios: &_ios
  os: osx
  osx_image: xcode11.5

_android: &_android
  language: android
  os: linux
  jdk: oraclejdk8
  android:
    components:
      - tools
      - build-tools-$ANDROID_BUILD_TOOLS_VERSION
      - android-$ANDROID_API_LEVEL
    licenses:
      - "android-sdk-preview-license-.+"
      - "android-sdk-license-.+"
      - "google-gdk-license-.+"

matrix:
  include:
    # additional `npm test` in directory
    # - env: ADDITIONAL_TESTS_DIR=./spec/testable-plugin/tests/foo
    #   <<: *_ios

    # # local tests, without saucelabs
    # - env: PLATFORM=local/browser
    #   <<: *_ios
    # - env: PLATFORM=local/ios-10.0
    #   <<: *_ios

    # many tests with saucelabs
    - env: PLATFORM=browser-chrome
    - env: PLATFORM=browser-firefox
    - env: PLATFORM=browser-safari
    - env: PLATFORM=browser-edge

    # - env: PLATFORM=ios-11.3
    #   <<: *_ios
    # - env: PLATFORM=ios-12.0
    #   <<: *_ios
    # - env: PLATFORM=ios-12.2
    #   <<: *_ios
    # - env: PLATFORM=android-5.1
    #   <<: *_android
    # - env: PLATFORM=android-6.0
    #   <<: *_android
    # - env: PLATFORM=android-7.0
    #   <<: *_android
    # - env: PLATFORM=android-7.1
    #   <<: *_android
    # - env: PLATFORM=android-8.0
    #   <<: *_android
    # - env: PLATFORM=android-8.1
    #   <<: *_android
    # - env: PLATFORM=android-9.0
    #   <<: *_android
    # - env: PLATFORM=android-10.0
    #   <<: *_android

before_install:
  # manually install Node for `language: android`
  - if [[ "$PLATFORM" =~ android ]]; then nvm install $TRAVIS_NODE_VERSION; fi
  - node --version
  - if [[ "$PLATFORM" =~ android ]]; then gradle --version; fi
  - if [[ "$PLATFORM" =~ ios ]]; then npm install -g ios-deploy; fi
  - npm install -g cordova serve
  # install paramedic if not running on paramedic repo
  - if ! [[ "$TRAVIS_REPO_SLUG" =~ cordova-paramedic ]]; then npm install -g github:apache/cordova-paramedic; fi

install:
  - npm install

before_script:
  - |
    if [[ "$TRAVIS_REPO_SLUG" =~ cordova-paramedic ]]; then 
      # when used in the cordova-paramedic repo
      TEST_COMMAND="npm run eslint"
      PARAMEDIC_PLUGIN_TO_TEST="./spec/testable-plugin/"
      PARAMEDIC_COMMAND="node main.js"
    else 
      # when used in any other (plugin) repo
      TEST_COMMAND="npm test"
      PARAMEDIC_PLUGIN_TO_TEST=$(pwd)
      PARAMEDIC_COMMAND="cordova-paramedic"
    fi
  - PARAMEDIC_BUILDNAME=travis-$TRAVIS_REPO_SLUG-$TRAVIS_JOB_NUMBER
  - |
    echo "Variables now are set to:"
    echo "TEST_COMMAND=$TEST_COMMAND"
    echo "ADDITIONAL_TESTS=$ADDITIONAL_TESTS"
    echo "PARAMEDIC_COMMAND=$PARAMEDIC_COMMAND"
    echo "PLATFORM=$PLATFORM"
    echo "PARAMEDIC_PLUGIN_TO_TEST=$PARAMEDIC_PLUGIN_TO_TEST"
    echo "PARAMEDIC_BUILDNAME=$PARAMEDIC_BUILDNAME"

script:
  - serve . &
  - $TEST_COMMAND
  - |
    if [[ "$ADDITIONAL_TESTS_DIR" != "" ]]; then
      cd $ADDITIONAL_TESTS_DIR && npm install && npm test;
    else 
      $PARAMEDIC_COMMAND --config ./pr/$PLATFORM --plugin $PARAMEDIC_PLUGIN_TO_TEST --buildName $PARAMEDIC_BUILDNAME; 
    fi
